/// <reference types="vite/client" />

// PUT ENV VARIABLES HERE FOR TYPES AND AUTOCORRECT
interface ImportMetaEnv {
  VITE_APP_FIREBASE_API_KEY: string;
  VITE_APP_FIREBASE_AUTH_DOMAIN: string;
  VITE_APP_FIREBASE_PROJECT_ID: string;
  VITE_APP_FIREBASE_STORAGE_BUCKET: string;
  VITE_APP_FIREBASE_MESSAGING_SENGER_ID: string;
  VITE_APP_FIREBASE_APP_ID: string;
}